module.exports = {
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  quoteProps: 'as-needed',
  jsxSingleQuote: true,
  trailingComma: 'es5',
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'avoid',
  endOfLine: 'lf',
  // React Native specific settings
  importOrder: [
    '^react$',
    '^react-native$',
    '^@react-navigation/(.*)$',
    '^@expo/(.*)$',
    '^expo-(.*)$',
    '^react-native-(.*)$',
    '<THIRD_PARTY_MODULES>',
    '^@/(.*)$',
    '^~/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  plugins: ['@trivago/prettier-plugin-sort-imports'],
};
